export const Constants = {
    SIGN_IN_LOADING: 'SIGN_IN_LOADING',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILED: 'SIGN_IN_FAILED',

    REGISTER_LOADING: 'REGISTER_LOADING',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILED: 'REGISTER_FAILED',

    REGISTER_TRUCK_LOADING: 'REGISTER_TRUCK_LOADING',
    REGISTER_TRUCK_SUCCESS: 'REGISTER_TRUCK_SUCCESS',
    REGISTER_TRUCK_FAILED: 'REGISTER_TRUCK_FAILED',

    LIST_RESERVATIONS_LOADING: 'LIST_RESERVATIONS_LOADING',
    LIST_RESERVATIONS_SUCCESS: 'LIST_RESERVATIONS_SUCCESS',
    LIST_RESERVATIONS_FAILED: 'LIST_RESERVATIONS_FAILED',

    BOOK_RESERVATION_LOADING: 'BOOK_RESERVATION_LOADING',
    BOOK_RESERVATION_SUCCESS: 'BOOK_RESERVATION_SUCCESS',
    BOOK_RESERVATION_FAILED: 'BOOK_RESERVATION_FAILED',

    ALERT_SUCCESS: 'ALERT_SUCCESS',
    ALERT_ERROR: 'ALERT_ERROR',
    ALERT_CLEAR: 'ALERT_CLEAR',

    SEARCH_TRUCK_LOADING: 'SEARCH_TRUCK_LOADING',
    SEARCH_TRUCK_SUCCESS: 'SEARCH_TRUCK_SUCCESS',
    SEARCH_TRUCK_FAILED: 'SEARCH_TRUCK_FAILED'

}